# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  karan

- task: CmdLine@2
  inputs:
    script: 'node index.js'
    workingDirectory: 'C:\Users\12784\Documents\pupeter'