

trigger:
- main

pool:
  karan

jobs:
- job: RunNodeJS
  displayName: 'Run Node.js'
  steps:
  - powershell: |
      # Navigate to the specified folder
      cd C:\Users\12784\Documents\pupeter
      
      # Run the node.js script
      node index.js
    displayName: 'Run Node.js Script'

  - powershell: |
      # Display success message
      Write-Host "Test cases ran successfully!"
    displayName: 'Display Success Message' 

  